### ISSUE TITLE
MySQL5.7.8 版本以下不支持 MAX_EXECUTION_TIME设置

### ISSUE THREAD

**Issue by simonhou** [lazzyfu/goInsight#236]
![image](https://user-images.githubusercontent.com/1290401/107138992-f1ce5c80-6952-11eb-8914-af49b96f8437.png)

可以增加下MySQL版本的兼容性说明，或者支持兼容低版本集群，毕竟5.6也还是主流。

**Comment by lazzyfu** [comment]
收到，谢谢，近期安排修复。

**Comment by lazzyfu** [comment]
注释掉MAX_EXECUTION_TIME，不影响使用
