### ISSUE TITLE
优化memory相关metrics名字

### ISSUE THREAD

**Issue by simonhou** [lazzyfu/goInsight#238]
![image](https://user-images.githubusercontent.com/1290401/107140337-39a5b180-695c-11eb-85ff-a04d9fb9999b.png)

- total_memory容易引起歧义，会以为是redis实例的总内存
-  另外加个maxmeory展示吧

**Comment by lazzyfu** [comment]
好的，我反馈给另外一个开发者，进行修复。

**Comment by lazzyfu** [comment]
大佬，可以加个微信，互相学习？
18810487655

**Comment by simonhou** [comment]
@lazzyfu 已加
