### ISSUE TITLE
请问这个可以用windows的pycharm开发工具运行吗?

### ISSUE THREAD

**Issue by cathylogs** [lazzyfu/goInsight#274]
请问这个可以用windows的pycharm开发工具运行吗?或者有没用教程呢,我运行不起来

**Comment by cathylogs** [comment]
![image](https://user-images.githubusercontent.com/39398991/129592361-a8d77081-0c57-4cd0-9c18-abd9751b04ea.png)
这是报错

**Comment by lazzyfu** [comment]
都可以，建议先熟悉django开发基础知识
