### ISSUE TITLE
开发者，您好，可以支持一下postgresql吗？

### ISSUE THREAD

**Issue by jinyan2049** [lazzyfu/goInsight#280]
开发者，您好，可以支持一下postgresql吗？
这是非常伟大的一款产品，但希望可以支持一下postgresql,谢谢

**Comment by lazzyfu** [comment]
不好意思，这么晚回复。

没用过pgsql，支持不了，更希望您结合自己的业务场景做二次开发

**Comment by jinyan2049** [comment]
谢谢，没事的！
