### ISSUE TITLE
咨询：能否修改项目开源协议？

### ISSUE THREAD

**Issue by leeworker** [lazzyfu/goInsight#321]
作者鼓励二开，但是我看协议是gpLv3，使用担心有污染风险 公司内部不允许使用。

**Comment by lazzyfu** [comment]
您好，放心使用，目前在使用golang重构，后续会更换许可。您可以加我微信: Lazzyfu


在 2023年10月9日 ***@***.***> 写道：


作者鼓励二开，但是我看协议是gpLv3，使用担心有污染风险 公司内部不允许使用。

**Comment by lazzyfu** [comment]
已更新为MIT
