### ISSUE TITLE
请问，是否需要帮忙实现接口 e2e 测试

### ISSUE THREAD

**Issue by LinuxSuRen** [lazzyfu/goInsight#375]
我已经帮助如下的一些项目实现了 e2e 接口测试，如果您希望能 e2e 的话，我愿意帮忙实现。期待收到回复。

https://github.com/LinuxSuRen/api-testing/discussions/284

**Comment by lazzyfu** [comment]
您好，实现e2e您这边有什么要求？

**Comment by LinuxSuRen** [comment]
只要是能相对容易地启动服务（例如：通过 docker compose），就可以了。我可以完成部分 API 的测试用例，但考虑到对您项目的业务不是很熟悉，更多完善还需要·一起来做。

**Comment by lazzyfu** [comment]
可以尝试下，不清楚您这边是否OK。
