### ISSUE TITLE
能不能告知一下怎么配置  config.yaml文件？

### ISSUE THREAD

**Issue by op-family** [lazzyfu/goInsight#376]
整个文档都没写怎么配置config.yaml ，启动项目后无法登录吗，点击登录没反应

![image](https://github.com/user-attachments/assets/f056db63-d7d7-4650-a54b-e7338b5d394b)

**Comment by lazzyfu** [comment]
请参考：https://github.com/lazzyfu/goInsight/wiki/Config

**Comment by lazzyfu** [comment]
如果有需要的话，您也可以加我个人微信：Lazzyfu
